# Generated by Django 5.1.4 on 2025-02-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_preparacion', 'EN PREPARACION'), ('pagado', 'PAGADO'), ('pendiente', 'PENDIENTE'), ('preparado', 'PREPARADO'), ('servido', 'SERVIDO'), ('reservado', 'RESERVADO')], default='pendiente', max_length=50),
        ),
    ]
