# Generated by Django 5.1.4 on 2025-02-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='platos',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='clientes',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='mesas',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='meseros',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='pedidos',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='personal_cocina_list',
        ),
        migrations.AddField(
            model_name='cliente',
            name='restaurante',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='pedidos.restaurante'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurante',
            field=models.OneToOneField(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='pedidos.restaurante'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='pedidos.restaurante'),
        ),
        migrations.AddField(
            model_name='mesero',
            name='restaurante',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='meseros', to='pedidos.restaurante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.restaurante'),
        ),
        migrations.AddField(
            model_name='personalcocina',
            name='restaurante',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='personal_cocina_list', to='pedidos.restaurante'),
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
        migrations.AddField(
            model_name='plato',
            name='menu',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='pedidos.menu'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_preparacion', 'EN PREPARACION'), ('pagado', 'PAGADO'), ('pendiente', 'PENDIENTE'), ('preparado', 'PREPARADO'), ('servido', 'SERVIDO'), ('reservado', 'RESERVADO')], default='PENDIENTE', max_length=50),
        ),
    ]
