# Generated by Django 5.1.4 on 2025-02-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_menu_platos_remove_restaurante_clientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='realizo_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_espera',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
