# Generated by Django 5.1.4 on 2025-02-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
    ]
